//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCollection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength =2)]
        public string Title { get; set; }
       
        [Display(Name ="Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =  "{0:yyy-MM-dd}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> ReleaseDate { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-z''-'\s\-]*$")]
        [StringLength(30)]
        public string Genre { get; set; }

        [Required]
        [Range(0,1000)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
    }
}
